[tools]
k6 = "latest"

[env]
K6_INFLUXDB_PUSH_INTERVAL="1s"
K6_OUT="influxdb=http://localhost:8086/k6"

[tasks."scenario"]
description = "Run k6"
run = 'k6 --config config/{{arg(name="config")}}.json run src/k6.js'

[tasks."start"]
description = "Start up the metrics stack"
run = "docker compose up --force-recreate -d"

[tasks."stop"]
description = "Stop the metrics stack"
run = "docker compose down"
